### ISSUE TITLE
Manque la Licence ?

### ISSUE THREAD

**Issue by Keyhaku** [doodz/OMVRemote2_git#1]
Hello,

Merci à toi d'avoir rendu ton application open source !
Pour finaliser le tout, il faut que tu choisisses une licence (et que tu créés le fichier LICENSE qui va bien dans le [repo)](https://help.github.com/articles/adding-a-license-to-a-repository/)

Voici quelques liens que j'ai glanés qui pourront t'aider à choisir
En Français
* https://blog.linuxjobs.fr/index.php?article9/rendre-public-du-code-sous-licence-libre-ecrit-dans-le-cadre-entreprise
* https://carlchenet.com/pourquoi-je-prefere-la-licence-gpl-aux-licences-permissives-type-bsdmit/

En Anglais
* http://oss-watch.ac.uk/resources/licdiff
* https://choosealicense.com/appendix/ (créé par Github)

Et si tu le souhaites tu peux ajouter un badge sur Github
https://github.com/ellerbrock/open-source-badges

**Comment by doodz** [comment]
Merci,
J'ai pris GPL V3.

Cordialement,

*{ Thibault HERVIOU }*
* Ingénieur informaticien .NET C#*
