### ISSUE TITLE
Cleartext HTTP traffic to host is not permitted

### ISSUE THREAD

**Issue by ebretteville** [doodz/OMVRemote2_git#14]
Hye,
On android Pie it seems that a parameter seems to be allowed to allow this kind of connection.
![57189887-23133080-6f14-11e9-87bd-edad219a6ced_2](https://user-images.githubusercontent.com/2842910/57226025-3efafd00-700e-11e9-9d6b-c23d357a97f3.jpg)

https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

**Comment by doodz** [comment]
Thank you very much for the feedback, I will see this in the week.

**Comment by ebretteville** [comment]
You're welcome. Thanks for your work

**Comment by ebretteville** [comment]
Oops I forgot to hide my public ip address do you mind if I remove the screenshot?

**Comment by doodz** [comment]
done

**Comment by doodz** [comment]
fix released on V1.2.2 today

**Comment by ebretteville** [comment]
Working again! Quick fix, thx!
