### ISSUE TITLE
widget options not right

### ISSUE THREAD

**Issue by happyreacer** [doodz/OMVRemote2_git#2]
on the first, - thanks for the nice android app!
But i have found a bug.
I activate the widget in my smartfone and have seen the options to deactivate the Uptime /CPU usage and used memory. There are all not this whot the name says. for example i have deactivate uptime and it disable the used memory.

Greetings

**Comment by doodz** [comment]
ok I will check that.
Thank you for your feedback.

**Comment by happyreacer** [comment]
In Version 1.1.31 only one Option not right. Deaktivate uptime the host info is deaktivated.
