### ISSUE TITLE
Plugins cant uninstall

### ISSUE THREAD

**Issue by happyreacer** [doodz/OMVRemote2_git#3]
I can Install plugins over the App. But the uninstall Option doesn't Work. The Button have no efect
May System:
Android 5.1 in a wiko Lenny 2
Openmediavault 3.0.74

**Comment by doodz** [comment]
Oops it's a regression.
This will be corrected in the next version.

**Comment by happyreacer** [comment]
Thanks, ist works in 1.1.31
