### ISSUE TITLE
WOL and suspend won't work on OMV3

### ISSUE THREAD

**Issue by dask2** [doodz/OMVRemote2_git#4]
Hi, thanks for the great app! 
Many things get easier than login with webbrowser.
I use your app since early times. It works perfect with OMV2.
After updating yesterday on OMV3 i can connect with your app, but suspend, hibernate and wol won't work anymore. Reboot and shutdown are ok. The defined MAC is correct.
Any ideas? 

thx, 
dask2

**Comment by doodz** [comment]
sorry for the late, i have not notified.

Unfortunately, the omv changes regularly and I have trouble following.
I'll see this quickly.
From memory, when I switched to OMV3 the WOL settings were disabled.

doods

**Comment by richard2000** [comment]
Nearly the same here with version 3.0.87 of OMV. Suspend works with your app, but not WOL.

I tried it with linux tool "wakeonlan" and it worked. So WOL is configured right at my OMV.
I tried it with my smartphone and also with my tablet. Both don't work.
WOL would be nice for syncing.

**Comment by richard2000** [comment]
WoL is still not working correct with your version by 19/01/2017 from play store.  After some research and network analyzing I got the problem with your app.
Your wol request is send to the configured IP e.g. 192.168.0.100 but omv waits for a broadcast to 255.255.255.255 at port 9 to the mac address.

You can verify this with:
tcpdump -i eth0 'port 9' -vvv

It should look like this:
```
19:17:18.028209 IP (tos 0x0, ttl 64, id 18700, offset 0, flags [DF], proto UDP (17), length 130)
    192.168.0.200.40407 > 255.255.255.255.discard: [udp sum ok] UDP, length 102
```
But your app sends:
```
19:18:57.673277 IP (tos 0x0, ttl 64, id 43853, offset 0, flags [DF], proto UDP (17), length 130)
    192.168.0.199.37251 > 192.168.0.100.discard: [udp sum ok] UDP, length 102
```
192.168.0.200 is "wakeonlan" program at my pc which is working (see my first post)
192.168.0.199 is your app at my android phone 
(found in this thread: https://forum.openmediavault.org/index.php/Thread/5887-Wake-on-Lan-not-working/)

You can verify it also with the android app "Wake On Lan" by Mike Webb. With this app it's possible to configure a destination client with 255.255.255.255 as IP and the right MAC. This also works. But it would be nicer to do all with your app.

**Comment by doodz** [comment]
I am so sorry.
Thank you for your feedback, I will work on it soon

**Comment by richard2000** [comment]
Great! If you need more information on network issue, contact me.

**Comment by doodz** [comment]
Hi,
I have send new release
It's possible to configure a destination client (broadcast) for WOL.
I stay tuned if you have still problems

**Comment by richard2000** [comment]
I've tested it right away and it worked!

The nas is must be running for saving the new broadcast address. (mine was in standby for testing)
Otherwise the app is not able to verify all parameters, but this is a good functionality for preventing errors in config.

**Comment by doodz** [comment]
Cool , I clossed.
