### ISSUE TITLE
[bug] can't access after password change

### ISSUE THREAD

**Issue by nr458h** [doodz/OMVRemote2_git#9]
Hi I have a completly new set up OMV NAS. And with the default credentials I can access the NAS with the app.

But when I change the default password (nothing else) I only can access through the browser.
In the app:
When I edit the current host the error says *an error occurred*. 
When I delete the host and create a new one it says *session not authenticated*

If I can provide a log, please give me a hinf were to look or what als need to be done.

Thanks in advance!

**Comment by doodz** [comment]
thank you for feedback,
I will work on this issue this weekend.

**Comment by doodz** [comment]
So strange :
I have not reproduce your error.
I Have changed my password from OMV web UI.
Then , on my app I have an error (User or password error) on the ui.
Then, I change password from "manage hosts", and it work.

Have you reproducted ?

**Comment by nr458h** [comment]
Thank you for the quick replaye

When I try to save the new password an error shows up.
So I'm not able to save the change, and when I go back to an other page it says again: Session not authenticated

**Comment by doodz** [comment]
he can't connect to the OMV server.
Login page say "an error occurend" when he can't joint server or other errors.
I have remove log at the moment ... RGPD(General Data Protection Regulation) comming :(.
brutal solution but hey, if you remove data and cache ?

**Comment by nr458h** [comment]
So even with a hole new smartphone nothing changes.

Remove data and or cache has no effect. 

In addition the question if this error can be related to the smartphones firewall (afwall+) or maybe with the settings of my wlan-router (fritz!box 7590)

any idea - would like to use this awesome app :(

**Comment by doodz** [comment]
I do not know. 
But what is certain is that if you delete data and cache and that it has no effect it does not come from the application.
